name: AutoCheckBJMF
on:
  workflow_dispatch: 
env: 
    ClassID: ${{ secrets.ClassID }}
    X: ${{ secrets.X }}
    Y: ${{ secrets.Y }}
    ACC: ${{ secrets.ACC }}
    SearchTime: ${{ secrets.SEARCHTIME }}
    MyCookie: ${{ secrets.MYCOOKIE }}
    token: ${{ secrets.TOKEN }}
    scheduletime: ${{ secrets.SCHEDULETIME }}
jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3        
      - name: Set up env
        run: |
             pip install schedule
             pip install beautifulsoup4
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
      - name: Checkin
        run: |
          python main.py 
